title:  Never coded; my experience with Github
author: DkPunch
email: randomnewdefaultskin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Follow me has I blog about my trials and tribulations having never
  coded a line before. (unless copy paste counts?) I will be
  working through learning how to make websites, use java script,
  python, even a workable app with real world function. 
  
# social links
twitter_username: @zemmett
github_username:  DkPunch

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-hacker
